start_win.quit()
    game_win=tkinter.Tk()
    game_win.title("HANGMAN")
    game_win.resizable(False, False)
    game_win.geometry("600x400+50+50")
    game_win.config(background="purple")
    #BG=tkinter.PhotoImage(file="C:\\Users\\Aluno\\Desktop\\10D2021-2022\PSI\\test\\hangman_startmenu.gif")
    #canvas2 = tkinter.Canvas(game_win, width = 400,height = 400)
    #canvas2.pack(fill = "both", expand = True)
    #canvas2.create_image( 0, 0, image = BG,anchor = "center")
    print(start_win)
        game_win.mainloop()

